### ISSUE TITLE
Reg() should support multiple clocks

### ISSUE THREAD

**Issue by ben-k** [ucb-bar/chisel3#206]
Reg() cannot currently instantiate with a clock other than the default.  In Reg.scala:

`val clock = Node(x._parent.get.clock) // TODO multi-clock
`

We need this feature for upcoming tapeout.  This is a regression from Chisel2.

**Comment by ben-k** [comment]
So for now we're planning to just wrap any bare `Reg` in a module call to work around this.  Going forward, though, either this should be implemented or the "TODO" comment should be removed.

**Comment by grebe** [comment]
@stevobailey and I would like to bump this

**Comment by aswaterman** [comment]
We have also been using the module work-around @ben-k mentioned.

The API for this deserves discussion.  Adding another parameter clock is viable, but do we do the same for RegEnable and RegReset, too?  Or only on Reg, since the multi-clock case is uncommon?

Another strategy entirely is to distinguish clock domains from modules by having clock scopes, something like

    withClock (myOtherClock) {
      val reg = Reg(UInt()) // this is clocked by myOtherClock
    }

This is more composable: if you write a function that generates registers, it will be affected by the surrounding withClock.  Otherwise, you'd have to resort to the module trick again.

**Comment by colinschmidt** [comment]
I like the withClock construct.

**Comment by mwachs5** [comment]
If we add a withClock construct, do we need a corresponding "withReset"?

**Comment by aswaterman** [comment]
Yeah (and probably withClockAndReset as a convenience).

**Comment by ducky64** [comment]
Possibly also worth deprecating the old Module clock/reset override constructors in favor of this?
Those seem to need support from the class extending Module to support clock reset overrides (so interface isn't consistent across all Modules).

**Comment by mwachs5** [comment]
Agreed with @ducky64. I find myself using a lot of the:

`
myModule.clock = someOtherClock `

rather than passing it in the constructor.

**Comment by mwachs5** [comment]
Extending this further than this issue's scope... would I be allowed to do

```
withClockAndReset (myOtherClock, myOtherReset) {
 val foo = Module (new Foo())
}
```

to also override module's clocks and resets (even though this is not necessary, just wondering what this construct would do)

**Comment by aswaterman** [comment]
that's what I'm thinking.

**Comment by ben-k** [comment]
I strongly support the proposal by @aswaterman - it would alleviate a lot of the current pain points of writing multiclock Chisel3.  In addition to `Reg`, there are several Chisel3 widgets (e.g., `Counter`) that do not extend `module` and so currently lack multiclock utility without an extra wrapper.

**Comment by aswaterman** [comment]
OK - I'll try to implement soon.

**Comment by terpstra** [comment]
I think this API seems quite ok.

However, I would not add 'withClock' and 'withRest'. There should only be 'withClockAndReset'. If you want to use the same reset, you can trivially pass it. Since you want the reset desertion to be synchronous with the clock, providing a combined method hopefully encourages proper usage.

**Comment by terpstra** [comment]
How does this interact with [Seq]Mem?

**Comment by aswaterman** [comment]
Agreed re: withClockAndReset only.

For [Seq]Mem, for which clocks are associated with ports, not the storage element itself, withClockAndReset will take effect for any ports created within.

**Comment by ducky64** [comment]
Any movement on the implementation of this? I would like to be able to use this too.
@aswaterman 
(if it's not projected within the next week or two, I can make an attempt at implementing this)

**Comment by aswaterman** [comment]
@ducky64 I started but got sidetracked by the deadline of the RISC-V workshop, which is next week.  I plan to finish it up after that, i.e., end of next week.

In the mean time, I'd just declare a Module and pass its constructor a clock and reset.

**Comment by aswaterman** [comment]
@jackkoenig will take care of the implementation

**Comment by jackkoenig** [comment]
Closed via https://github.com/ucb-bar/chisel3/pull/509!!!
