### ISSUE TITLE
edu.berkeley.cs#chisel_2.11;3.1-SNAPSHOT: not found

### ISSUE THREAD

**Issue by MahdiNazemi** [ucb-bar/chisel3#518]
Hi,

I have cloned all four repositories related to chisel3 and ran `sbt compile` and `sbt publish-local` on them. However, when I add `libraryDependencies += "edu.berkeley.cs" %% "chisel" % "3.1-SNAPSHOT"` to my build.sbt file, I get the following error during compilation:

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: edu.berkeley.cs#chisel_2.11;3.1-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

Is there something I am doing wrong?

Thanks,
Matt

**Comment by ucbjrl** [comment]
The library dependency you've shown is a dependency on a chisel2 SNAPSHOT.
You should be using chisel3:

libraryDependencies += "edu.berkeley.cs" %% "chisel3" % "3.1-SNAPSHOT"

Check the build.sbt in chisel-testers. As much as we would have liked to,
we couldn't rename "chisel" to "chisel2" due to compatibility issues.

**Comment by MahdiNazemi** [comment]
Thanks a lot for your prompt response. I change the dependency to chisel3 and the error is gone. You may need to update the README file for chisel3 to reflect this. Currently, what I had written in my original post is written in the README file.

**Comment by ucbjrl** [comment]
Thanks Mahdi. I have a pull request to update the README.
