### ISSUE TITLE
Revisit Vec wiring once the directionality / vec / binding refactors happen.

### ISSUE THREAD

**Issue by ucbjrl** [ucb-bar/chisel3#522]
Instances of:
```
Vec.fill(n)(Module(new FullAdder()).io)
```
have to be replaced (if possible) with:
```
Array.fill(n)(Module(new FullAdder()).io)
```
since Vec wiring is now mono-connect, due to lack of direction on cloned `Vec` elements.

See 375e2b6a0a456c55298d82837d28986de6211ebc

**Comment by sdtwigg** [comment]
I strongly doubt the mutability of the Array is actually desired so should advocate using a more appropriate Scala data structure.

Since random-indexing is highly likely, amusingly Vector is probably the best choice. To avoid confusion of Vec vs. Vector can use IndexedSeq, which is basically equivalent.

**Comment by jackkoenig** [comment]
Here's a branch with a test that now fails but used to succeed:

https://github.com/ucb-bar/chisel3/tree/vec-of-modules

**Comment by ducky64** [comment]
Ok, traced through this.

The issue seems to be that Vecs create an internal Wire, but Wire bindings are undirectioned, so the BiConnect operation gets really confused.
